apiVersion: v1
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  statusbadge.enabled: 'true'
  accounts.ci-user: login, apiKey
  repositories: |
    - sshPrivateKeySecret:
        key: ls-service-user-ssh-key
        name: github-creds
      url: {{ .Values.spec.source.repoURL }}
    - name: lightspeed
      type: helm
      url: https://lightspeedhq.jfrog.io/artifactory/helm
      usernameSecret:
        name: artifactory-access
        key: username
      passwordSecret:
        name: artifactory-access
        key: password
    - name: lightspeed-other
      type: helm
      url: https://lightspeedhq.jfrog.io/lightspeedhq/helm
      usernameSecret:
        name: artifactory-access
        key: username
      passwordSecret:
        name: artifactory-access
        key: password
    - sshPrivateKeySecret:
        name: gatekeeper-manifest-repository
        key: deploy-key
      url: git@github.com:lightspeedretail/gatekeeper-library.git
  repository.credentials: |
    - url: git@github.com
      sshPrivateKeySecret:
        key: ls-service-user-ssh-key
        name: github-creds
    - url: git@github.com:lightspeedretail/gatekeeper-library.git
      sshPrivateKeySecret:
        name: gatekeeper-manifest-repository
        key: deploy-key
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-2.9.5
  name: argocd-cm
  namespace: argocd
